version: "3"
services:
  mongo:
    image: mongo
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27019:27017"
    networks:
      - backend
  api:
    image: node:12.16-slim
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "yarn start"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
